import React from "react";
import styled from "@emotion/styled";
/**
 * `<HomeDesktopLight>` ('Home Desktop (Light)')
 * - [Open in Figma](https://figma.com/file/1qy0z8fQA9Jx7TzHCEEfMG?node-id=227:13010)
 * - [Open in Grida](https://code.grida.co/files/1qy0z8fQA9Jx7TzHCEEfMG?node=227:13010)
 * 
 * 
 * ---
 * @example
 * ```tsx
 * import React from "react";
 * 
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <HomeDesktopLight/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f664bd27-d700-4b5e-83f2-7d8d361c9438)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 * 
 * 
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://1qy0z8fQA9Jx7TzHCEEfMG/227:13010 -->
 */
export function HomeDesktopLight() {
  return (
    <RootWrapperHomeDesktopLight>
      <TemplateBaseLayout>
        <Header>
          <Container>
            <LogoT3Q>
              <T3Q xmlns="http://www.w3.org/2000/svg">
                <path fill="rgb(0, 119, 192)" d="M7.63456 0L0 0L0 5.0897L7.63456 5.0897L7.63456 0Z"/>
              </T3Q>
            </LogoT3Q>
            <Navigation>
              <LinkText>
                <NaN_0001>
                  T3Q.ai 플랫폼
                </NaN_0001>
              </LinkText>
              <LinkText>
                <NaN_0001>
                  Ai 훈민정음 플랫폼
                </NaN_0001>
              </LinkText>
              <LinkText>
                <NaN_0001>
                  Ai 엔진
                </NaN_0001>
              </LinkText>
              <LinkText>
                <NaN_0001>
                  닥터 앤서 Ai 플랫폼
                </NaN_0001>
              </LinkText>
              <LinkText>
                <NaN_0001>
                  T3Q 회사소개
                </NaN_0001>
              </LinkText>
            </Navigation>
            <Switcher>
              <RoundedRectangle/>
              <Ellipse/>
            </Switcher>
          </Container>
        </Header>
        <Footer>
          <Copyright2022T3QAllRightsReserved>
            Copyright ⓒ 2022 T3Q All rights reserved.
          </Copyright2022T3QAllRightsReserved>
          <Container_0001>
            <_3028601605618>
              서울특별시 구로구 디지털로 30길 28 마리오타워 601~605, 618호
            </_3028601605618>
            <Tel0263447660Fax0263447661>
              Tel : 02-6344-7660 / Fax : 02-6344-7661
            </Tel0263447660Fax0263447661>
            <LogoT3Q_0001>
              <T3Q_0001 xmlns="http://www.w3.org/2000/svg">
                <path fill="white" d="M6 0L0 0L0 4L6 4L6 0Z"/>
              </T3Q_0001>
            </LogoT3Q_0001>
            <LinkIcon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/fd2d8a6e-59d4-4e62-b34c-972ad9f58ac4" alt="icon"/>
            <LinkIcon_0001 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f9144798-05f0-4b2a-ab52-5f0ab1d75b62" alt="icon"/>
          </Container_0001>
          <Border>
            <Top/>
          </Border>
        </Footer>
      </TemplateBaseLayout>
      <Wrapper>
        <HomeIntro>
          <Container_0002>
            <Hero>
              <T3QAi>
                T3Q는 인공지능, 빅데이터 플랫폼을 만드는 회사입니다.
              </T3QAi>
              <AiAsAService>
                서비스형 인공지능(Ai as a Service) 플랫폼 세상은 만들고자 하는 음식과  재료만 있으면 요리사가 원하는 요리를 만들 수 있는 공유주방과 같은 개념입니다.
              </AiAsAService>
              <ButtonScrolling>
                <DownArrow src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/180f58fc-4463-4960-bd23-9d5cc80fd50f" alt="image of DownArrow"/>
              </ButtonScrolling>
              <FrameVideo>
                <Video src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/0c9d950f-86b4-42fc-8296-2d9041765ad6" alt="image of Video"/>
                <ButtonPlayPause src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/dd0c7258-809d-49b2-a2b8-ed1ab8889d6e" alt="icon"/>
              </FrameVideo>
            </Hero>
          </Container_0002>
        </HomeIntro>
        <HomeService>
          <Container_0003>
            <SectionTitle>
              <TextContainer>
                <Heading>
                  서비스
                </Heading>
                <T3Q_0002>
                  T3Q 
                </T3Q_0002>
              </TextContainer>
              <Deco/>
              <Deco_0001/>
            </SectionTitle>
            <ServiceList>
              <ServiceItem>
                <Box/>
                <Top_0001>
                  <_01>
                    01
                  </_01>
                  <Rectangle44/>
                </Top_0001>
                <TextInfo>
                  <NaN_0006>
                    인공지능 플랫폼
                  </NaN_0006>
                  <ArtificialIntelligencePlatform>
                    Artificial intelligence platform
                  </ArtificialIntelligencePlatform>
                  <T3QEdgeAi>
                    T3Q의 인공지능 플랫폼은 대응이 가능한  Edge AI 시스템으로 효율성과 고가용성을 보장합니다.  
                  </T3QEdgeAi>
                </TextInfo>
              </ServiceItem>
              <ServiceItem_0001>
                <Box/>
                <Top_0001>
                  <_01>
                    04
                  </_01>
                  <Rectangle44/>
                </Top_0001>
                <TextInfo>
                  <NaN_0006>
                    AI 훈민정음
                  </NaN_0006>
                  <ArtificialIntelligencePlatform>
                    ai hunminjungum
                  </ArtificialIntelligencePlatform>
                  <T3QEdgeAi>
                    T3Q의 인공지능 플랫폼은 대응이 가능한  Edge AI 시스템으로 효율성과 고가용성을 보장합니다.  
                  </T3QEdgeAi>
                </TextInfo>
              </ServiceItem_0001>
              <ServiceItem_0002>
                <Box/>
                <Top_0001>
                  <_01>
                    02
                  </_01>
                  <Rectangle44/>
                </Top_0001>
                <TextInfo>
                  <NaN_0006>
                    인공지능 서비스 개발
                  </NaN_0006>
                  <ArtificialIntelligencePlatform>
                    Artificial intelligence service
                  </ArtificialIntelligencePlatform>
                  <T3QEdgeAi>
                    T3Q의 인공지능 플랫폼은 대응이 가능한  Edge AI 시스템으로 효율성과 고가용성을 보장합니다.  
                  </T3QEdgeAi>
                </TextInfo>
              </ServiceItem_0002>
              <ServiceItem_0003>
                <Box/>
                <Top_0001>
                  <_01>
                    05
                  </_01>
                  <Rectangle44/>
                </Top_0001>
                <TextInfo>
                  <NaN_0006>
                    닥터앤서 의료 플랫폼
                  </NaN_0006>
                  <ArtificialIntelligencePlatform>
                    DR.ANSWER
                  </ArtificialIntelligencePlatform>
                  <T3QEdgeAi>
                    T3Q의 인공지능 플랫폼은 대응이 가능한  Edge AI 시스템으로 효율성과 고가용성을 보장합니다.  
                  </T3QEdgeAi>
                </TextInfo>
              </ServiceItem_0003>
              <ServiceItem_0004>
                <Box/>
                <Top_0001>
                  <_01>
                    03
                  </_01>
                  <Rectangle44/>
                </Top_0001>
                <TextInfo>
                  <NaN_0006>
                    빅데이터 플랫폼
                  </NaN_0006>
                  <ArtificialIntelligencePlatform>
                    bigdata platform
                  </ArtificialIntelligencePlatform>
                  <T3QEdgeAi>
                    T3Q의 인공지능 플랫폼은 대응이 가능한  Edge AI 시스템으로 효율성과 고가용성을 보장합니다.  
                  </T3QEdgeAi>
                </TextInfo>
              </ServiceItem_0004>
              <ServiceItem_0005>
                <Box/>
                <Top_0001>
                  <_01>
                    06
                  </_01>
                  <Rectangle44/>
                </Top_0001>
                <TextInfo>
                  <NaN_0006>
                    Edge 인공지능
                  </NaN_0006>
                  <ArtificialIntelligencePlatform>
                    edge intelligence 
                  </ArtificialIntelligencePlatform>
                  <T3QEdgeAi>
                    T3Q의 인공지능 플랫폼은 대응이 가능한  Edge AI 시스템으로 효율성과 고가용성을 보장합니다.  
                  </T3QEdgeAi>
                </TextInfo>
              </ServiceItem_0005>
            </ServiceList>
          </Container_0003>
        </HomeService>
        <HomeStory>
          <HomeStory_0001>
            <Container_0004>
              <SectionTitle_0001>
                <TextContainer>
                  <Heading>
                    스토리
                  </Heading>
                  <T3Q_0002>
                    T3Q 
                  </T3Q_0002>
                </TextContainer>
                <Deco/>
                <Deco_0001/>
              </SectionTitle_0001>
              <NumberData>
                <Year>
                  <_15>
                    15
                  </_15>
                  <YearsInBusiness>
                    2007년 비즈니스 시작
                  </YearsInBusiness>
                </Year>
                <Member>
                  <_80>
                    80+
                  </_80>
                  <DesignersAndDevelopers>
                    고급 / 전문  기술 인력 구성
                  </DesignersAndDevelopers>
                </Member>
              </NumberData>
              <NaN_0012>
                인공지능 서비스 개발자를 위한 개발 툴, 개발된 서비스의 학습과 추론을  실행하는 환경, 준비된 업무 전문 회사가 인공지능 비즈니스를 할 수 있도록 지원하는 지능화 비즈니스 플랫폼을  제공합니다.
              </NaN_0012>
              <T3QAi_0001>
                T3Q.ai 플랫폼
              </T3QAi_0001>
              <NaN_0013>
                빅데이터 플랫폼과 인공지능 플랫폼으로 구성되어 개발 작업이 필요 없이 알고리즘 설정으로 서비스 개발이 가능하며 고객의 요청에 따라 서비스를 개발하는 주문형 서비스가 가능합니다
              </NaN_0013>
              <LinkButton>
                <Group3>
                  <Rectangle10/>
                  <LinkText_0005>
                    About T3Q
                  </LinkText_0005>
                </Group3>
              </LinkButton>
              <ImageSlide>
                <Image14 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/361b76e4-5552-4b7e-978b-9ab6d8d590fc" alt="image of Image14"/>
                <Image3 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9cd62517-82df-46f2-bdc1-6e25637e417e" alt="image of Image3"/>
                <Image13 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/11e5ee4d-fbb5-4549-af39-7b3485063d8e" alt="image of Image13"/>
                <Image15 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6e957aa7-3b7a-4690-bfce-656b62f1f6a7" alt="image of Image15"/>
                <Image3_0001 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/dc447285-ef43-42c4-9d3f-8fb35757f4d4" alt="image of Image3"/>
              </ImageSlide>
            </Container_0004>
          </HomeStory_0001>
        </HomeStory>
        <HomePartners>
          <Container_0005>
            <SectionTitle_0002>
              <TextContainer_0002>
                <Heading>
                  파트너스
                </Heading>
                <T3Q_0002>
                  T3Q 
                </T3Q_0002>
              </TextContainer_0002>
              <Deco/>
              <Deco_0001/>
            </SectionTitle_0002>
            <List>
              <Group8635>
                <Rectangle8/>
                <MaskGroup>
                  <MaskGroup_0001>
                    <Image18 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/08a23b55-84ba-409c-a823-ca93d1ecbbb8" alt="image of Image18"/>
                  </MaskGroup_0001>
                </MaskGroup>
              </Group8635>
              <Group8638>
                <Rectangle8/>
                <MaskGroup>
                  <MaskGroup_0003>
                    <Image25 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/83c71a3a-6976-4449-acc5-8fbad7c4f57f" alt="image of Image25"/>
                  </MaskGroup_0003>
                </MaskGroup>
              </Group8638>
              <Group8641>
                <Rectangle8/>
                <MaskGroup>
                  <MaskGroup_0003>
                    <Image22 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/01d42cdf-9f96-4dd7-9dee-5775de2fb541" alt="image of Image22"/>
                  </MaskGroup_0003>
                </MaskGroup>
              </Group8641>
              <Group8644>
                <Rectangle8/>
                <MaskGroup>
                  <MaskGroup_0003>
                    <Image30 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/cb3b3c60-2460-4699-a866-f2de6bfce59e" alt="image of Image30"/>
                  </MaskGroup_0003>
                </MaskGroup>
              </Group8644>
              <Group8647>
                <Rectangle8/>
                <MaskGroup>
                  <MaskGroup_0003>
                    <Image27 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/cc69766d-131e-4f9d-88be-13b19b1aa830" alt="image of Image27"/>
                  </MaskGroup_0003>
                </MaskGroup>
              </Group8647>
              <Group8636>
                <Rectangle8/>
                <MaskGroup>
                  <MaskGroup_0003>
                    <Image28 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9ff7e64b-369b-42e7-ab78-f7ead59fd521" alt="image of Image28"/>
                  </MaskGroup_0003>
                </MaskGroup>
              </Group8636>
              <Group8639>
                <Rectangle8/>
                <MaskGroup>
                  <MaskGroup_0003>
                    <Image24 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/4dfc9756-78c7-4af3-9d61-f62ef23f5b36" alt="image of Image24"/>
                  </MaskGroup_0003>
                </MaskGroup>
              </Group8639>
              <Group8642>
                <Rectangle8/>
                <MaskGroup>
                  <MaskGroup_0003>
                    <Image20 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ee53dcc2-be40-42f0-baff-25c71f96a971" alt="image of Image20"/>
                  </MaskGroup_0003>
                </MaskGroup>
              </Group8642>
              <Group8645>
                <Rectangle8/>
                <MaskGroup>
                  <MaskGroup_0003>
                    <Image26 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/959451da-68b7-4814-9673-a332a1cfe2f6" alt="image of Image26"/>
                  </MaskGroup_0003>
                </MaskGroup>
              </Group8645>
              <Group8637>
                <Rectangle8/>
                <MaskGroup>
                  <MaskGroup_0003>
                    <Image23 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/86ae7500-47fd-430a-be28-649b6ee84c64" alt="image of Image23"/>
                  </MaskGroup_0003>
                </MaskGroup>
              </Group8637>
              <Group8640>
                <Rectangle8/>
                <MaskGroup>
                  <MaskGroup_0003>
                    <Image19 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ae3ebee8-130d-4878-a199-cb4c02f534e6" alt="image of Image19"/>
                  </MaskGroup_0003>
                </MaskGroup>
              </Group8640>
              <Group8643>
                <Rectangle8/>
                <MaskGroup>
                  <MaskGroup_0003>
                    <Image21 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/109cc899-57e2-4909-9a52-2be79b02573e" alt="image of Image21"/>
                  </MaskGroup_0003>
                </MaskGroup>
              </Group8643>
              <Group8646>
                <Rectangle8/>
                <MaskGroup>
                  <MaskGroup_0003>
                    <Image29 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/7ab2a4cd-190d-4ab9-8469-a8b61df65741" alt="image of Image29"/>
                  </MaskGroup_0003>
                </MaskGroup>
              </Group8646>
            </List>
          </Container_0005>
        </HomePartners>
        <HomePlatform>
          <Container_0006>
            <SectionTitle_0003>
              <TextContainer>
                <Heading>
                  플랫폼
                </Heading>
                <T3Q_0002>
                  T3Q 
                </T3Q_0002>
              </TextContainer>
              <Deco/>
              <Deco_0001/>
            </SectionTitle_0003>
            <SlideSection>
              <MaskGroup_0026>
                <MaskGroup_0027>
                  <DocterAnswer src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f20682e1-be81-4171-9c46-331762530d9d" alt="image of DocterAnswer"/>
                </MaskGroup_0027>
              </MaskGroup_0026>
              <Group8634>
                <Group8633>
                  <Rectangle5/>
                  <Rectangle6/>
                </Group8633>
                <_14>
                  1/4
                </_14>
              </Group8634>
              <Buttons>
                <ButtonArrow src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/26523a68-6cef-49b5-838d-ecb43b95d00b" alt="icon"/>
                <ButtonArrow_0001 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/53eaf90c-29e0-4ff6-9200-6a7cdef34351" alt="icon"/>
              </Buttons>
              <ButtonSlidePlayPause src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/979380b4-23ec-463d-80fe-2deceb80132c" alt="icon"/>
            </SlideSection>
            <T3QAi_0002>
              T3Q.ai 플랫폼
            </T3QAi_0002>
            <LinkButton_0001>
              <Group3_0001>
                <Rectangle10/>
                <LinkText_0006>
                  Detail View
                </LinkText_0006>
              </Group3_0001>
            </LinkButton_0001>
            <NaN_0014>
              빅데이터 플랫폼과 인공지능 플랫폼으로 구성되어 개발 작업이 필요 없이 알고리즘 설정으로 서비스 개발이 가능하며 고객의 요청에 따라 서비스를 개발하는 주문형 서비스가 가능합니다
            </NaN_0014>
          </Container_0006>
        </HomePlatform>
        <HomeProcess>
          <Container_0007>
            <SectionTitle_0004>
              <TextContainer_0002>
                <Heading>
                  프로세스
                </Heading>
                <T3Q_0002>
                  T3Q 
                </T3Q_0002>
              </TextContainer_0002>
              <Deco/>
              <Deco_0001/>
            </SectionTitle_0004>
            <Horizontal>
              <Step01>
                <Step>
                  <_01_0006>
                    01
                  </_01_0006>
                  <StepText>
                    데이터 수집
                  </StepText>
                </Step>
                <Content>
                  <Image17 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e1108c7a-e712-4e12-890c-d31d1b97fcd1" alt="image of Image17"/>
                  <T3QCep>
                    T3Q.cep
                  </T3QCep>
                  <WhiteBox>
                    <Box_0006/>
                    <Text>
                      <NaN_0015>
                        빅데이터 저장소
                      </NaN_0015>
                      <NaN_0016>
                        빅데이터 실시간
                      </NaN_0016>
                    </Text>
                  </WhiteBox>
                </Content>
                <Arrow src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/60b550a6-39c5-43d7-969a-7190176a3d09" alt="image of Arrow"/>
              </Step01>
              <Step02>
                <Step_0001>
                  <_01_0006>
                    02
                  </_01_0006>
                  <StepText_0001>
                    실시간 지능화
                  </StepText_0001>
                </Step_0001>
                <Group8627>
                  <RobotGfb277C28319201 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/bbf0d3f6-01a0-44d8-a732-65323c6596c8" alt="image of RobotGfb277C28319201"/>
                  <T3QDl>
                    T3Q.dl
                  </T3QDl>
                  <Group8625>
                    <Rectangle1/>
                    <Group8631>
                      <NaN_0017>
                        인공지능 플랫폼
                      </NaN_0017>
                    </Group8631>
                  </Group8625>
                </Group8627>
                <Vector9 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/2236e368-177b-4fcf-9c3e-0ae91d83c2ca" alt="image of Vector9"/>
              </Step02>
              <Step03>
                <Step_0001>
                  <_01_0006>
                    03
                  </_01_0006>
                  <StepText_0002>
                    자료 분석
                  </StepText_0002>
                </Step_0001>
                <Group8627_0001>
                  <AnalyticsG5060B5F0719201 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/29461dd7-7733-4fe2-b6ac-57c5e00efd03" alt="image of AnalyticsG5060B5F0719201"/>
                  <T3QAi_0003>
                    T3Q.ai
                  </T3QAi_0003>
                  <Group8625_0001>
                    <Rectangle1/>
                    <NaN_0018>
                      인공지능 빅데이터  통합 플랫폼
                    </NaN_0018>
                    <EdgeAiABox>
                      Edge AI를 위한 A-Box
                    </EdgeAiABox>
                  </Group8625_0001>
                </Group8627_0001>
                <Vector9_0001 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8f616a15-4e1d-49db-8194-01a802b30d10" alt="image of Vector9"/>
              </Step03>
              <Step04>
                <Step_0001>
                  <_01_0006>
                    04
                  </_01_0006>
                  <StepText>
                    서비스 구현
                  </StepText>
                </Step_0001>
                <Group8627_0002>
                  <Sl10182036860111 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/dc8d3130-074d-4497-908f-54a6ed8c7c73" alt="image of Sl10182036860111"/>
                  <T3QAiCloud>
                    T3Q.ai Cloud
                  </T3QAiCloud>
                  <Group8625_0002>
                    <Rectangle1/>
                    <AiAsAService_0001>
                      클라우드 기반  AI as a Service<br/>
(서비스형 인공지능 플랫폼)
                    </AiAsAService_0001>
                  </Group8625_0002>
                </Group8627_0002>
              </Step04>
            </Horizontal>
          </Container_0007>
        </HomeProcess>
        <HomePlayverse>
          <Container_0008>
            <SectionTitle_0005>
              <TextContainer_0005>
                <Heading_0005>
                  ai playverse
                </Heading_0005>
                <T3Q_0002>
                  T3Q 
                </T3Q_0002>
              </TextContainer_0005>
              <Deco/>
              <Deco_0001/>
            </SectionTitle_0005>
            <DiagramSection>
              <Diagram>
                <Group8652>
                  <Ellipse16 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/4ffcba07-5afc-4f58-961d-534e6146b75f" alt="image from ellipse"/>
                  <Platform>
                    Platform
                  </Platform>
                </Group8652>
                <Group8650>
                  <Ellipse17 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/d03a2c15-9dcf-48a7-9a68-50c672e6989a" alt="image from ellipse"/>
                  <BootCamp>
                    Boot Camp
                  </BootCamp>
                </Group8650>
                <Group8650>
                  <Ellipse17 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6057bf31-0ef4-4130-8a9f-a687be72bf95" alt="image from ellipse"/>
                  <MarketPlace>
                    Market Place
                  </MarketPlace>
                </Group8650>
                <Group8650>
                  <Ellipse17 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/5f6de979-3aed-4ca1-aa9c-17b266ec212d" alt="image from ellipse"/>
                  <Request>
                    Request
                  </Request>
                </Group8650>
                <Group8653>
                  <Ellipse15/>
                  <AiPlayverse>
                    AI Playverse
                  </AiPlayverse>
                </Group8653>
                <Group8654>
                  <Subtract src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a76d71f0-db71-4fc7-b4d1-17a7ff8ab67a" alt="image of Subtract"/>
                  <Support>
                    Support
                  </Support>
                </Group8654>
              </Diagram>
              <NaN_0019>
                빅데이터 플랫폼과 인공지능 플랫폼으로 구성되어 개발 작업이 필요 없이 알고리즘 설정으로 서비스 개발이 가능하며 고객의 요청에 따라 서비스를 개발하는 주문형 서비스가 가능합니다
              </NaN_0019>
              <NaN_0020>
                해당 항목을 선택하면 자세한 설명을 보실 수 있습니다.
              </NaN_0020>
            </DiagramSection>
          </Container_0008>
        </HomePlayverse>
      </Wrapper>
    </RootWrapperHomeDesktopLight>
  )
}

const RootWrapperHomeDesktopLight = styled.div`
	min-height: 100vh;
	background-color: white;
	border-radius: false;
	position: relative;
`;

const TemplateBaseLayout = styled.div`
	overflow: hidden;
	background-color: white;
	border-radius: false;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const Header = styled.div`
	height: 108px;
	overflow: hidden;
	background-color: white;
	border-radius: false;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
`;

const Container = styled.div`
	width: 1144px;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + 0px)) - 572px));
	top: 0px;
	bottom: 0px;
`;

const LogoT3Q = styled.div`
	width: 83px;
	height: 26px;
	border-radius: false;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 0px)) - 13px));
`;

const T3Q = styled.svg`
	width: 83px;
	height: 25px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Navigation = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	border-radius: false;
	box-sizing: border-box;
	position: absolute;
	top: calc((calc((50% + 0px)) - 16px));
	right: 116px;
	width: 639px;
	height: 32px;
`;

const LinkText = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 10px;
	border-radius: false;
	box-sizing: border-box;
	padding: 3px 16px;
`;

const NaN_0001 = styled.span`
	color: rgb(102, 102, 102);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 500;
	line-height: 160%;
	text-align: center;
`;

const Switcher = styled.div`
	width: 28px;
	height: 16px;
	border-radius: false;
	position: absolute;
	left: 1116px;
	top: 46px;
`;

const RoundedRectangle = styled.div`
	border: solid 1px rgb(43, 120, 211);
	border-radius: 8px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const Ellipse = styled.div`
	background-color: rgb(43, 120, 211);
	border-radius: 12px / 12px;
	position: absolute;
	left: 2px;
	top: 2px;
	right: 14px;
	bottom: 2px;
`;

const Footer = styled.div`
	height: 303px;
	overflow: hidden;
	background-color: rgb(9, 24, 42);
	border-radius: false;
	position: absolute;
	left: 0px;
	right: 0px;
	bottom: 0px;
`;

const Copyright2022T3QAllRightsReserved = styled.span`
	color: rgb(179, 179, 179);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 150%;
	text-align: center;
	position: absolute;
	left: calc((calc((50% + -344px)) - 112px));
	bottom: 47px;
`;

const Container_0001 = styled.div`
	width: 1144px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + 0px)) - 572px));
	top: 0px;
	bottom: 0px;
`;

const _3028601605618 = styled.span`
	color: rgb(179, 179, 179);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 150%;
	text-align: left;
	position: absolute;
	left: 116px;
	top: 100px;
`;

const Tel0263447660Fax0263447661 = styled.span`
	color: rgb(179, 179, 179);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 150%;
	text-align: center;
	position: absolute;
	left: 117px;
	top: 126px;
`;

const LogoT3Q_0001 = styled.div`
	width: 65px;
	height: 20px;
	border-radius: false;
	position: absolute;
	left: 116px;
	top: 48px;
`;

const T3Q_0001 = styled.svg`
	width: 65px;
	height: 20px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const LinkIcon = styled.img`
	width: 40px;
	height: 40px;
	object-fit: cover;
	position: absolute;
	left: 988px;
	top: 40px;
`;

const LinkIcon_0001 = styled.img`
	width: 40px;
	height: 40px;
	object-fit: cover;
	position: absolute;
	left: 924px;
	top: 40px;
`;

const Border = styled.div`
	width: 1600px;
	height: 0px;
	position: absolute;
	left: 0px;
	top: 1px;
`;

const Top = styled.div`
	height: 0px;
	border-top: solid 1px rgb(17, 48, 85);
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
`;

const Wrapper = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	border-radius: false;
	box-sizing: border-box;
	position: absolute;
	left: 0px;
	top: 108px;
	width: 1600px;
	height: 6676px;
`;

const HomeIntro = styled.div`
	width: 1600px;
	height: 1440px;
	background-color: white;
	border-radius: false;
	position: relative;
`;

const Container_0002 = styled.div`
	width: 1600px;
	height: 1444px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + 0px)) - 800px));
	top: 0px;
`;

const Hero = styled.div`
	width: 1600px;
	height: 1444px;
	overflow: hidden;
	background-color: white;
	border-radius: false;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const T3QAi = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 32px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 500;
	line-height: 130%;
	text-align: left;
	width: 400px;
	position: absolute;
	left: 344px;
	top: 120px;
`;

const AiAsAService = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: left;
	width: 912px;
	position: absolute;
	left: 344px;
	top: 1122px;
`;

const ButtonScrolling = styled.div`
	width: 42px;
	height: 42px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + 0px)) - 21px));
	bottom: 118px;
`;

const DownArrow = styled.img`
	width: 36px;
	height: 0px;
	object-fit: cover;
	position: absolute;
	left: 21px;
	top: 3px;
	transform: rotate(-270deg);
	transform-origin: top left;
`;

const FrameVideo = styled.div`
	width: 1376px;
	height: 742px;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + 0px)) - 688px));
	top: 308px;
`;

const Video = styled.img`
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const ButtonPlayPause = styled.img`
	width: 36px;
	height: 36px;
	object-fit: cover;
	position: absolute;
	left: calc((calc((50% + 0px)) - 18px));
	top: calc((calc((50% + 0px)) - 18px));
`;

const HomeService = styled.div`
	width: 1600px;
	height: 860px;
	background-color: white;
	border-radius: false;
	position: relative;
`;

const Container_0003 = styled.div`
	width: 1146px;
	height: 716px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + -6px)) - 573px));
	top: 72px;
`;

const SectionTitle = styled.div`
	width: 190px;
	height: 46px;
	border-radius: false;
	position: absolute;
	left: 484px;
	top: 0px;
`;

const TextContainer = styled.div`
	width: 172px;
	height: 47px;
	position: absolute;
	left: 8px;
	top: 0px;
`;

const Heading = styled.span`
	color: rgb(26, 26, 26);
	text-overflow: ellipsis;
	font-size: 36px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: left;
	text-transform: uppercase;
	position: absolute;
	left: 73px;
	top: 0px;
	right: 0px;
`;

const T3Q_0002 = styled.span`
	color: rgb(43, 120, 211);
	text-overflow: ellipsis;
	font-size: 36px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	letter-spacing: -2px;
	line-height: 130%;
	text-align: center;
	text-transform: uppercase;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Deco = styled.div`
	width: 8px;
	height: 8px;
	background-color: rgb(43, 120, 211);
	border-radius: false;
	position: absolute;
	right: 0px;
	bottom: 0px;
`;

const Deco_0001 = styled.div`
	width: 8px;
	height: 8px;
	background-color: rgb(43, 120, 211);
	border-radius: false;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const ServiceList = styled.div`
	width: 1140px;
	height: 584px;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + 3px)) - 570px));
	top: 114px;
`;

const ServiceItem = styled.div`
	width: 344px;
	height: 262px;
	border-radius: false;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Box = styled.div`
	background-color: white;
	border-radius: 4px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const Top_0001 = styled.div`
	width: 320px;
	height: 23px;
	border-radius: false;
	position: absolute;
	left: 12px;
	top: 12px;
`;

const _01 = styled.span`
	color: rgb(43, 120, 211);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle44 = styled.div`
	width: 290px;
	height: 4px;
	background-color: rgb(51, 51, 51);
	border-radius: false;
	position: absolute;
	left: 30px;
	top: 11px;
`;

const TextInfo = styled.div`
	width: 278px;
	height: 140px;
	border-radius: false;
	position: absolute;
	left: 12px;
	top: 57px;
`;

const NaN_0006 = styled.span`
	color: rgb(43, 120, 211);
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 42px;
`;

const ArtificialIntelligencePlatform = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: left;
	text-transform: uppercase;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const T3QEdgeAi = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 150%;
	text-align: left;
	width: 278px;
	position: absolute;
	left: 0px;
	top: 98px;
`;

const ServiceItem_0001 = styled.div`
	width: 344px;
	height: 262px;
	border-radius: false;
	position: absolute;
	left: 4px;
	top: 322px;
`;

const ServiceItem_0002 = styled.div`
	width: 344px;
	height: 262px;
	border-radius: false;
	position: absolute;
	left: 400px;
	top: 4px;
`;

const ServiceItem_0003 = styled.div`
	width: 344px;
	height: 262px;
	border-radius: false;
	position: absolute;
	left: 400px;
	top: 322px;
`;

const ServiceItem_0004 = styled.div`
	width: 344px;
	height: 262px;
	border-radius: false;
	position: absolute;
	left: 796px;
	top: 4px;
`;

const ServiceItem_0005 = styled.div`
	width: 344px;
	height: 262px;
	border-radius: false;
	position: absolute;
	left: 796px;
	top: 322px;
`;

const HomeStory = styled.div`
	width: 1600px;
	height: 944px;
	overflow: hidden;
	background-color: white;
	border-radius: false;
	position: relative;
`;

const HomeStory_0001 = styled.div`
	height: 804px;
	border-radius: false;
	position: absolute;
	left: -36px;
	top: 140px;
	right: -34px;
`;

const Container_0004 = styled.div`
	width: 1522px;
	height: 732px;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + 0px)) - 761px));
	top: 0px;
`;

const SectionTitle_0001 = styled.div`
	width: 190px;
	height: 47px;
	border-radius: false;
	position: absolute;
	left: 646px;
	top: 0px;
`;

const NumberData = styled.div`
	width: 260px;
	height: 73px;
	border-radius: false;
	position: absolute;
	left: 937px;
	top: 115px;
`;

const Year = styled.div`
	width: 109px;
	height: 71px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	left: 151px;
	top: 0px;
`;

const _15 = styled.span`
	color: rgb(43, 120, 211);
	text-overflow: ellipsis;
	font-size: 40px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 150%;
	text-align: left;
	position: absolute;
	left: 31px;
	top: 0px;
`;

const YearsInBusiness = styled.span`
	color: rgb(43, 120, 211);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 150%;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 54px;
`;

const Member = styled.div`
	width: 128px;
	height: 73px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const _80 = styled.span`
	color: rgb(43, 120, 211);
	text-overflow: ellipsis;
	font-size: 40px;
	font-family: Roboto, sans-serif;
	font-weight: 900;
	line-height: 150%;
	text-align: left;
	position: absolute;
	left: 36px;
	top: 0px;
`;

const DesignersAndDevelopers = styled.span`
	color: rgb(43, 120, 211);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 150%;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 56px;
`;

const NaN_0012 = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: left;
	width: 541px;
	position: absolute;
	left: 285px;
	top: 115px;
`;

const T3QAi_0001 = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: center;
	position: absolute;
	left: 689px;
	top: 623px;
`;

const NaN_0013 = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: center;
	width: 655px;
	position: absolute;
	left: 414px;
	top: 674px;
`;

const LinkButton = styled.div`
	width: 87px;
	height: 21px;
	border-radius: false;
	position: absolute;
	left: 285px;
	top: 231px;
`;

const Group3 = styled.div`
	width: 87px;
	height: 21px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle10 = styled.div`
	height: 6px;
	background-color: rgba(43, 120, 211, 0.3);
	border-radius: false;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 7px)) - 3px));
	right: 0px;
`;

const LinkText_0005 = styled.span`
	color: rgb(43, 120, 211);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: center;
	position: absolute;
	left: 2px;
	top: calc((calc((50% + 0px)) - 11px));
	right: 1px;
`;

const ImageSlide = styled.div`
	width: 1522px;
	height: 220px;
	border-radius: false;
	position: absolute;
	left: 0px;
	top: 348px;
`;

const Image14 = styled.img`
	width: 260px;
	height: 180px;
	object-fit: cover;
	position: absolute;
	left: 949px;
	top: 20px;
`;

const Image3 = styled.img`
	width: 260px;
	height: 220px;
	object-fit: cover;
	position: absolute;
	left: 633px;
	top: 0px;
`;

const Image13 = styled.img`
	width: 260px;
	height: 180px;
	object-fit: cover;
	position: absolute;
	left: 316px;
	top: 20px;
`;

const Image15 = styled.img`
	width: 260px;
	height: 220px;
	object-fit: cover;
	position: absolute;
	left: 1262px;
	top: 0px;
`;

const Image3_0001 = styled.img`
	width: 260px;
	height: 220px;
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const HomePartners = styled.div`
	width: 1600px;
	height: 446px;
	overflow: hidden;
	background-color: white;
	border-radius: false;
	position: relative;
`;

const Container_0005 = styled.div`
	width: 828px;
	height: 234px;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + 0px)) - 414px));
	top: 140px;
`;

const SectionTitle_0002 = styled.div`
	width: 228px;
	height: 46px;
	border-radius: false;
	position: absolute;
	left: 300px;
	top: 0px;
`;

const TextContainer_0002 = styled.div`
	width: 205px;
	height: 47px;
	position: absolute;
	left: 8px;
	top: 0px;
`;

const List = styled.div`
	width: 828px;
	height: 120px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	left: 0px;
	top: 114px;
`;

const Group8635 = styled.div`
	width: 104px;
	height: 40px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle8 = styled.div`
	width: 104px;
	height: 40px;
	border-radius: 6px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const MaskGroup = styled.div`
	width: 94px;
	height: 34px;
	position: absolute;
	left: 2px;
	top: 3px;
`;

const MaskGroup_0001 = styled.div`
	width: 94px;
	height: 34px;
	overflow: hidden;
	position: absolute;
	left: 0px;
	top: 0px;
	border-radius: false;
`;

const Image18 = styled.img`
	width: 79px;
	height: 34px;
	object-fit: cover;
	position: absolute;
	left: 11px;
	top: 0px;
`;

const Group8638 = styled.div`
	width: 104px;
	height: 40px;
	position: absolute;
	left: 360px;
	top: 0px;
`;

const MaskGroup_0003 = styled.div`
	width: 94px;
	height: 34px;
	overflow: hidden;
	position: absolute;
	left: 0px;
	top: 0px;
	border-radius: 5px;
`;

const Image25 = styled.img`
	width: 83px;
	height: 40px;
	object-fit: cover;
	position: absolute;
	left: 7px;
	top: -5px;
`;

const Group8641 = styled.div`
	width: 104px;
	height: 40px;
	position: absolute;
	left: 724px;
	top: 0px;
`;

const Image22 = styled.img`
	width: 58px;
	height: 35px;
	object-fit: cover;
	position: absolute;
	left: 21px;
	top: 0px;
`;

const Group8644 = styled.div`
	width: 104px;
	height: 40px;
	position: absolute;
	left: 0px;
	top: 80px;
`;

const Image30 = styled.img`
	width: 75px;
	height: 33px;
	object-fit: cover;
	position: absolute;
	left: 11px;
	top: 1px;
`;

const Group8647 = styled.div`
	width: 104px;
	height: 40px;
	position: absolute;
	left: 482px;
	top: 79px;
`;

const Image27 = styled.img`
	width: 88px;
	height: 41px;
	object-fit: cover;
	position: absolute;
	left: 6px;
	top: -4px;
`;

const Group8636 = styled.div`
	width: 104px;
	height: 40px;
	position: absolute;
	left: 120px;
	top: 0px;
`;

const Image28 = styled.img`
	width: 95px;
	height: 26px;
	object-fit: cover;
	position: absolute;
	left: 3px;
	top: 4px;
`;

const Group8639 = styled.div`
	width: 104px;
	height: 40px;
	position: absolute;
	left: 480px;
	top: 0px;
`;

const Image24 = styled.img`
	width: 79px;
	height: 46px;
	object-fit: cover;
	position: absolute;
	left: 10px;
	top: -6px;
`;

const Group8642 = styled.div`
	width: 104px;
	height: 40px;
	position: absolute;
	left: 360px;
	top: 80px;
`;

const Image20 = styled.img`
	width: 83px;
	height: 29px;
	object-fit: cover;
	position: absolute;
	left: 7px;
	top: 3px;
`;

const Group8645 = styled.div`
	width: 104px;
	height: 40px;
	position: absolute;
	left: 124px;
	top: 80px;
`;

const Image26 = styled.img`
	width: 83px;
	height: 46px;
	object-fit: cover;
	position: absolute;
	left: 8px;
	top: -6px;
`;

const Group8637 = styled.div`
	width: 104px;
	height: 40px;
	position: absolute;
	left: 240px;
	top: 0px;
`;

const Image23 = styled.img`
	width: 67px;
	height: 40px;
	object-fit: cover;
	position: absolute;
	left: 17px;
	top: -3px;
`;

const Group8640 = styled.div`
	width: 104px;
	height: 40px;
	position: absolute;
	left: 602px;
	top: 0px;
`;

const Image19 = styled.img`
	width: 95px;
	height: 41px;
	object-fit: cover;
	position: absolute;
	left: 3px;
	top: -3px;
`;

const Group8643 = styled.div`
	width: 104px;
	height: 40px;
	position: absolute;
	left: 240px;
	top: 80px;
`;

const Image21 = styled.img`
	width: 79px;
	height: 36px;
	object-fit: cover;
	position: absolute;
	left: 10px;
	top: -1px;
`;

const Group8646 = styled.div`
	width: 104px;
	height: 40px;
	position: absolute;
	left: 604px;
	top: 77px;
`;

const Image29 = styled.img`
	width: 103px;
	height: 30px;
	object-fit: cover;
	position: absolute;
	left: -3px;
	top: 3px;
`;

const HomePlatform = styled.div`
	width: 1600px;
	height: 1090px;
	overflow: hidden;
	background-color: white;
	border-radius: false;
	position: relative;
`;

const Container_0006 = styled.div`
	width: 1144px;
	height: 878px;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + 0px)) - 572px));
	top: 140px;
`;

const SectionTitle_0003 = styled.div`
	width: 194px;
	height: 46px;
	border-radius: false;
	position: absolute;
	left: 475px;
	top: 0px;
`;

const SlideSection = styled.div`
	width: 1144px;
	height: 527px;
	border-radius: false;
	position: absolute;
	left: 0px;
	top: 97px;
`;

const MaskGroup_0026 = styled.div`
	width: 1144px;
	height: 526px;
	position: absolute;
	left: 0px;
	top: 17px;
`;

const MaskGroup_0027 = styled.div`
	overflow: hidden;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
	border-radius: false;
`;

const DocterAnswer = styled.img`
	width: 1203px;
	height: 629px;
	object-fit: cover;
	position: absolute;
	left: -59px;
	top: -1px;
`;

const Group8634 = styled.div`
	width: 563px;
	height: 21px;
	position: absolute;
	left: 208px;
	top: 503px;
`;

const Group8633 = styled.div`
	width: 528px;
	height: 2px;
	position: absolute;
	left: 0px;
	top: 9px;
`;

const Rectangle5 = styled.div`
	width: 528px;
	height: 2px;
	background-color: white;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + 0px)) - 264px));
	bottom: 0px;
`;

const Rectangle6 = styled.div`
	width: 335px;
	height: 2px;
	background-color: rgb(43, 120, 211);
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + -97px)) - 168px));
	bottom: 0px;
`;

const _14 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 150%;
	text-align: center;
	position: absolute;
	left: calc((calc((50% + 271px)) - 11px));
	bottom: 0px;
`;

const Buttons = styled.div`
	width: 1073px;
	height: 24px;
	position: absolute;
	left: 35px;
	top: 266px;
`;

const ButtonArrow = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	left: 24px;
	top: calc((calc((50% + 24px)) - 12px));
`;

const ButtonArrow_0001 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	top: calc((calc((50% + 24px)) - 12px));
	right: -24px;
`;

const ButtonSlidePlayPause = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	left: 777px;
	top: 501px;
`;

const T3QAi_0002 = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 26px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 500;
	line-height: 130%;
	text-align: center;
	position: absolute;
	left: 495px;
	top: 694px;
`;

const LinkButton_0001 = styled.div`
	width: 94px;
	height: 21px;
	border-radius: false;
	position: absolute;
	left: 525px;
	top: 857px;
`;

const Group3_0001 = styled.div`
	width: 94px;
	height: 21px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const LinkText_0006 = styled.span`
	color: rgb(43, 120, 211);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: center;
	position: absolute;
	left: 3px;
	top: calc((calc((50% + 0px)) - 11px));
	right: 3px;
`;

const NaN_0014 = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: center;
	width: 535px;
	position: absolute;
	left: 305px;
	top: 744px;
`;

const HomeProcess = styled.div`
	width: 1600px;
	height: 974px;
	overflow: hidden;
	background-color: white;
	border-radius: false;
	position: relative;
`;

const Container_0007 = styled.div`
	width: 890px;
	height: 779px;
	border-radius: false;
	position: absolute;
	left: 475px;
	top: 140px;
`;

const SectionTitle_0004 = styled.div`
	width: 229px;
	height: 46px;
	border-radius: false;
	position: absolute;
	left: 211px;
	top: 0px;
`;

const Horizontal = styled.div`
	height: 665px;
	background-color: white;
	border-radius: false;
	position: absolute;
	left: 0px;
	top: 114px;
	right: -4010px;
`;

const Step01 = styled.div`
	width: 1000px;
	height: 658px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	left: 0px;
	top: 7px;
`;

const Step = styled.div`
	width: 123px;
	height: 143px;
	border-radius: false;
	position: absolute;
	left: 255px;
	top: 515px;
`;

const _01_0006 = styled.span`
	color: rgb(128, 128, 128);
	text-overflow: ellipsis;
	font-size: 104px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	letter-spacing: -1px;
	line-height: 130%;
	text-align: center;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const StepText = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 23px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: center;
	position: absolute;
	left: calc((calc((50% + 0px)) - 57px));
	top: 113px;
`;

const Content = styled.div`
	width: 716px;
	height: 440px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Image17 = styled.img`
	width: 640px;
	height: 440px;
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const T3QCep = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 40px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: left;
	position: absolute;
	left: 26px;
	top: 12px;
`;

const WhiteBox = styled.div`
	width: 248px;
	height: 149px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	left: 468px;
	top: 248px;
	backdrop-filter: blur(4px);
`;

const Box_0006 = styled.div`
	width: 248px;
	height: 149px;
	background-color: rgba(255, 255, 255, 0.9);
	border: solid 1px white;
	border-radius: 6px;
	position: absolute;
	left: 0px;
	top: 0px;
	opacity: 0.8;
`;

const Text = styled.div`
	width: 118px;
	height: 64px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	left: 64px;
	top: 44px;
`;

const NaN_0015 = styled.span`
	color: rgb(26, 26, 26);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: center;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const NaN_0016 = styled.span`
	color: rgb(26, 26, 26);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: center;
	position: absolute;
	left: 0px;
	top: 35px;
`;

const Arrow = styled.img`
	width: 80px;
	height: 50px;
	object-fit: cover;
	position: absolute;
	left: 992px;
	top: 195px;
	transform: rotate(-180deg);
	transform-origin: top left;
`;

const Step02 = styled.div`
	width: 987px;
	height: 658px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	left: 1256px;
	top: 0px;
`;

const Step_0001 = styled.div`
	width: 123px;
	height: 143px;
	border-radius: false;
	position: absolute;
	left: 258px;
	top: 515px;
`;

const StepText_0001 = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 23px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: center;
	position: absolute;
	left: calc((calc((50% + 1px)) - 68px));
	top: 113px;
`;

const Group8627 = styled.div`
	width: 726px;
	height: 440px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const RobotGfb277C28319201 = styled.img`
	width: 640px;
	height: 440px;
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const T3QDl = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 40px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: left;
	position: absolute;
	left: 12px;
	top: 12px;
`;

const Group8625 = styled.div`
	width: 248px;
	height: 149px;
	position: absolute;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	left: 478px;
	top: 255px;
	backdrop-filter: blur(4px);
`;

const Rectangle1 = styled.div`
	width: 248px;
	height: 149px;
	background-color: rgba(255, 255, 255, 0.9);
	border: solid 1px white;
	border-radius: 6px;
	position: absolute;
	left: 0px;
	top: 0px;
	opacity: 0.8;
`;

const Group8631 = styled.div`
	width: 118px;
	height: 29px;
	position: absolute;
	left: 63px;
	top: 60px;
`;

const NaN_0017 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: center;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Vector9 = styled.img`
	width: 80px;
	height: 50px;
	object-fit: cover;
	position: absolute;
	left: 987px;
	top: 195px;
	transform: rotate(-180deg);
	transform-origin: top left;
`;

const Step03 = styled.div`
	width: 971px;
	height: 658px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	left: 2518px;
	top: 0px;
`;

const StepText_0002 = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 23px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: center;
	position: absolute;
	left: calc((calc((50% + 1px)) - 46px));
	top: 113px;
`;

const Group8627_0001 = styled.div`
	width: 715px;
	height: 440px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const AnalyticsG5060B5F0719201 = styled.img`
	width: 640px;
	height: 440px;
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const T3QAi_0003 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 40px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: left;
	position: absolute;
	left: 12px;
	top: 12px;
`;

const Group8625_0001 = styled.div`
	width: 248px;
	height: 149px;
	position: absolute;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	left: 467px;
	top: 221px;
	backdrop-filter: blur(4px);
`;

const NaN_0018 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: center;
	position: absolute;
	left: 53px;
	top: 26px;
`;

const EdgeAiABox = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: center;
	position: absolute;
	left: 42px;
	top: 91px;
`;

const Vector9_0001 = styled.img`
	width: 80px;
	height: 50px;
	object-fit: cover;
	position: absolute;
	left: 971px;
	top: 195px;
	transform: rotate(-180deg);
	transform-origin: top left;
`;

const Step04 = styled.div`
	width: 713px;
	height: 658px;
	overflow: hidden;
	border-radius: false;
	position: absolute;
	left: 3778px;
	top: 0px;
`;

const Group8627_0002 = styled.div`
	width: 713px;
	height: 440px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Sl10182036860111 = styled.img`
	width: 640px;
	height: 440px;
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const T3QAiCloud = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 40px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: left;
	position: absolute;
	left: 12px;
	top: 12px;
`;

const Group8625_0002 = styled.div`
	width: 248px;
	height: 149px;
	position: absolute;
	box-shadow: 0px 4px 4px  rgba(0, 0, 0, 0.25);
	left: 465px;
	top: 221px;
	backdrop-filter: blur(4px);
`;

const AiAsAService_0001 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: center;
	position: absolute;
	left: 24px;
	top: 22px;
`;

const HomePlayverse = styled.div`
	width: 1600px;
	height: 922px;
	overflow: hidden;
	background-color: white;
	border-radius: false;
	position: relative;
`;

const Container_0008 = styled.div`
	width: 660px;
	height: 710px;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + 0px)) - 330px));
	top: 140px;
`;

const SectionTitle_0005 = styled.div`
	width: 332px;
	height: 46px;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + 0px)) - 166px));
	top: 0px;
`;

const TextContainer_0005 = styled.div`
	width: 314px;
	height: 47px;
	position: absolute;
	left: 8px;
	top: 0px;
`;

const Heading_0005 = styled.span`
	color: rgb(26, 26, 26);
	text-overflow: ellipsis;
	font-size: 36px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 700;
	line-height: 130%;
	text-align: left;
	text-transform: uppercase;
	position: absolute;
	left: 73px;
	top: 0px;
	right: -2px;
`;

const DiagramSection = styled.div`
	width: 660px;
	height: 596px;
	border-radius: false;
	position: absolute;
	left: calc((calc((50% + 0px)) - 330px));
	top: 114px;
`;

const Diagram = styled.div`
	width: 476px;
	height: 476px;
	border-radius: false;
	position: absolute;
	left: 92px;
	top: 24px;
`;

const Group8652 = styled.div`
	width: 305px;
	height: 305px;
	position: absolute;
	left: 84px;
	top: 84px;
`;

const Ellipse16 = styled.img`
	width: 305px;
	height: 305px;
	object-fit: contain;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Platform = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 140%;
	text-align: center;
	position: absolute;
	left: 117px;
	top: 243px;
`;

const Group8650 = styled.div`
	width: 476px;
	height: 476px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Ellipse17 = styled.img`
	width: 476px;
	height: 476px;
	object-fit: contain;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const BootCamp = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 140%;
	text-align: center;
	position: absolute;
	left: 393px;
	top: 306px;
`;

const MarketPlace = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 140%;
	text-align: center;
	position: absolute;
	left: 185px;
	top: 428px;
`;

const Request = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 140%;
	text-align: center;
	position: absolute;
	left: 26px;
	top: 314px;
`;

const Group8653 = styled.div`
	width: 110px;
	height: 110px;
	position: absolute;
	left: 182px;
	top: 183px;
`;

const Ellipse15 = styled.div`
	width: 110px;
	height: 110px;
	box-shadow: 4px 4px 13px  rgba(0, 0, 0, 0.25);
	background-color: white;
	border-radius: 110px / 110px;
	position: absolute;
	left: 0px;
	top: 110px;
`;

const AiPlayverse = styled.span`
	color: rgb(77, 77, 77);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 140%;
	text-align: center;
	position: absolute;
	left: 17px;
	top: 28px;
`;

const Group8654 = styled.div`
	width: 275px;
	height: 138px;
	position: absolute;
	left: 100px;
	top: 100px;
`;

const Subtract = styled.img`
	width: 275px;
	height: 138px;
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Support = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 140%;
	text-align: center;
	position: absolute;
	left: 100px;
	top: 26px;
`;

const NaN_0019 = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: center;
	position: absolute;
	left: calc((calc((50% + 0px)) - 330px));
	top: 0px;
`;

const NaN_0020 = styled.span`
	color: rgb(51, 51, 51);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Spoqa Han Sans Neo", sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: center;
	position: absolute;
	left: calc((calc((50% + 0px)) - 172px));
	top: 570px;
`;

